name: PR Review

on:
  pull_request_target:
    types:
      - opened
      - reopened

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  pr_check:
    runs-on: ubuntu-latest
    steps:
      - name: Exit if PR opened by FrogAi
        if: ${{ github.actor == 'FrogAi' }}
        run: |
          echo "PR opened or reopened by FrogAi. No action needed."
          exit 0

      - name: Close PR if target branch is invalid
        if: ${{ github.base_ref != 'MAKE-PRS-HERE' }}
        run: |
          gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            -f body="Please submit your pull request to the \"MAKE-PRS-HERE\" branch."

          gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
            -X PATCH \
            -f state='closed'

      - name: Thank for PR if target branch is valid
        if: ${{ github.base_ref == 'MAKE-PRS-HERE' }}
        run: |
          gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            -f body="Thank you for your PR! If you're not already in the FrogPilot Discord, [feel free to join](https://discord.FrogPilot.download) and let me know you've opened a PR!"
