name: Schedule FrogPilot Update

on:
  workflow_dispatch:
    inputs:
      scheduled_date:
        description: "Enter the date to update the \"FrogPilot\" branch (YYYY-MM-DD)"
        required: true

env:
  BRANCH: FrogPilot-Staging

jobs:
  schedule-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
          fetch-depth: 2

      - name: Switch to target branch
        run: |
          git checkout ${{ env.BRANCH }} || git checkout -b ${{ env.BRANCH }}

      - name: Capture last commit details
        run: |
          last_date=$(git log -1 --format="%cI")
          last_message=$(git log -1 --format="%B")

          echo "LAST_DATE=$last_date" >> $GITHUB_ENV
          echo "LAST_MESSAGE<<EOF" >> $GITHUB_ENV
          echo "$last_message" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create update date file
        run: echo "${{ github.event.inputs.scheduled_date }}" > .github/update_date

      - name: Commit update date file
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          git add .github/update_date
          git commit -m "Scheduled update for ${{ github.event.inputs.scheduled_date }}"

      - name: Squash update date file commit
        run: |
          git reset --soft HEAD~1

          GIT_COMMITTER_DATE="${{ env.LAST_DATE }}" git commit --amend -m "${{ env.LAST_MESSAGE }}"

          git push origin HEAD --force
