name: Update Tinygrad

on:
  workflow_dispatch:

jobs:
  update_tinygrad:
    name: Update Tinygrad
    runs-on:
      - self-hosted
      - c3x

    steps:
      - name: Get version
        id: get_version
        run: |
          VERSION=$(grep -oP '^VERSION\s*=\s*"\K[^"]+' /data/openpilot/frogpilot/assets/model_manager.py)
          echo "VERSION=$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Install zip
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Zip Tinygrad folders
        run: |
          mkdir -p /data/tmp/frogpilot_tinygrad
          cd /data/openpilot

          ZIP_NAME="Tinygrad_${{ steps.get_version.outputs.version }}.zip"
          zip -r "/data/tmp/frogpilot_tinygrad/$ZIP_NAME" frogpilot/tinygrad_modeld tinygrad

      - name: Clone GitLab repo
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          cd /data/tmp/frogpilot_tinygrad
          git clone --depth 1 --branch Tinygrad https://oauth2:${GITLAB_TOKEN}@gitlab.com/FrogAi/FrogPilot-Resources.git

      - name: Push updated Tinygrad
        run: |
          cd repo

          cp ../Tinygrad_*.zip .

          git config user.name "James"
          git config user.email "91348155+FrogAi@users.noreply.github.com"

          git add Tinygrad_*.zip
          git commit -m "Updated Tinygrad: Tinygrad_${{ steps.get_version.outputs.version }}.zip"
          git push origin Tinygrad

      - name: Cleanup temporary files
        run: |
          rm -rf /data/tmp/frogpilot_tinygrad
